const events = [
  {
    title: '3 persons booked',
    start: new Date(2019, 10, 10, 11, 0, 0),
    end: new Date(2019, 10, 10, 12, 0, 0),
    color: '#e91e63',
    room: '123',
    floor: '123',
    branch: '123',
    availableSlot: 3,
    members: [
      {
        name: 'Vinoth Vinoth Vinoth Vinoth Vinoth Vinoth',
        profileimage: '/assets/images/avatar/A18.jpg',
        mobile: '1234567890',
        status: 'Booked',
        paxCount: 1,
      },
      {
        name: 'Vinoth',
        profileimage: '',
        mobile: '1234567890',
        status: 'Cancelled',
        paxCount: 1,
      },
      {
        name: 'Vinoth',
        profileimage: '',
        mobile: '1234567890',
        status: 'CheckedIn',
        checkInTime: '',
        checkOutTime: '',
        paxCount: 1,
      },
      {
        name: 'Vinoth Vinoth Vinoth Vinoth Vinoth Vinoth',
        profileimage: '/assets/images/avatar/A18.jpg',
        mobile: '1234567890',
        status: 'No Show',
        paxCount: 1,
      },
      {
        name: 'Vinoth Vinoth Vinoth Vinoth Vinoth Vinoth',
        profileimage: '/assets/images/avatar/A18.jpg',
        mobile: '1234567890',
        status: 'Booked',
        paxCount: 1,
      },
      {
        name: 'Vinoth Vinoth Vinoth Vinoth Vinoth Vinoth',
        profileimage: '/assets/images/avatar/A18.jpg',
        mobile: '1234567890',
        status: 'Booked',
        paxCount: 1,
      },
    ],
    image: '/assets/images/avatar/A18.jpg',
    name: 'Vinoth',
    mobile: '1234567890',
  },
  {
    title: '3 persons booked',
    start: new Date(2019, 10, 10, 14, 0, 0),
    end: new Date(2019, 10, 10, 15, 0, 0),
    color: '#2196f3',
    room: '123',
    floor: '123',
    branch: '123',
    availableSlot: 2,
    members: [
      {
        name: 'Vinoth Vinoth Vinoth Vinoth Vinoth Vinoth',
        profileimage: '/assets/images/avatar/A18.jpg',
        mobile: '1234567890',
        status: 'Booked',
      },
      {
        name: 'Vinoth',
        profileimage: '',
        mobile: '1234567890',
        status: 'Booked',
      },
      {
        name: 'Vinoth',
        profileimage: '',
        mobile: '1234567890',
        status: 'Booked',
      },
    ],
    image: '/assets/images/avatar/A18.jpg',
    name: 'Vinoth',
    mobile: '1234567890',
  },
  {
    title: 'Fully booked',
    start: new Date(2019, 10, 12, 12, 0, 0),
    end: new Date(2019, 10, 12, 13, 0, 0),
    color: '#9e9e9e',
    room: '123',
    floor: '123',
    branch: '123',
    availableSlot: 0,
    members: [
      {
        name: 'Vinoth Vinoth Vinoth Vinoth Vinoth Vinoth',
        profileimage: '/assets/images/avatar/A18.jpg',
        mobile: '1234567890',
        status: 'Booked',
      },
      {
        name: 'Vinoth',
        profileimage: '',
        mobile: '1234567890',
        status: 'Booked',
      },
      {
        name: 'Vinoth',
        profileimage: '',
        mobile: '1234567890',
        status: 'Booked',
      },
      {
        name: 'Vinoth',
        profileimage: '',
        mobile: '1234567890',
        status: 'Booked',
      },
      {
        name: 'Vinoth',
        profileimage: '',
        mobile: '1234567890',
        status: 'Booked',
      },
      {
        name: 'Vinoth',
        profileimage: '',
        mobile: '1234567890',
        status: 'Booked',
      },
    ],
    image: '/assets/images/avatar/A18.jpg',
    name: 'Vinoth',
    mobile: '1234567890',
  },
];
export default events;
