const settingsData = {
  general: {
    openby: '07:10',
    closeby: '07:10',
    openingHoursFrom: {
      hours: '07',
      minutes: '00',
    },
    openingHoursTo: {
      hours: '07',
      minutes: '00',
    },
    workingdays: ['Mon'],
    noneWorkingdays: ['Mon'],
    accountType: 'Agency',
    agencyName: 'EcoVacs Tech Pvt Ltd.',
    language: 'English',
    dateFormat: 'DD/MM/YYYY',
    decimalSeparator: 'Decimal Point',
    currency: 'USD',
    street: 'St. Street 34',
    zipCode: '827102',
    city: 'NYC',
    country: 'New York',
    state: 'New York',
    phoneNumber: '+91 9372371278',
    alternateNumber: '+91 9372371278',
  },
  accounting: {
    accountHolder: 'EcoVacs Tech  Pvt.  Ltd',
    bankName: 'Canara Bank',
    countryOfBank: 'India',
    accountNumber: '312718521635726626',
    swiftBic: 'CNRBINBBXXX',
    taxId: 'SAK31234JK21',
    vatId: 'KH239J88JJ22UI',
    ifsc: 'CNRB0000540',
  },
  invoicing: {
    language: 'English',
    dateFormat: 'DD/MM/YYYY',
    currency: 'MYR',
    email: 'abc@email.com',
    decimalSeparator: 'Decimal Point',
    prefix: 'ABC',
    invoicePeriod: 'Daily',
    invoiceFormat: 'ABC-[INV/PO]-DD-MM-YYYY-running-number',
    receiptFormat: 'ABC-[INV/PO]-DD-MM-YYYY-running-number-Rnn',
    clientName: 'Client & Recipient Name',
    introductionText: 'Not Set',
    taxInfo: [],
    taxType: 'SST',
    taxValue: '0.00%',
    concludingText:
      'Bank Transfer to <Bank Name> <Account#> with your childs name stated as reference',
    paymentDeadline: '3 days',
    logo: '/assets/images/logo.png',
  },
  paymentGateway: {
    isEnabled: true,
    provider: 'curlec',
    providerKey1: 'DD/MM/YYYY',
    providerKey2: 'DD/MM/YYYY',
    currency: 'MYR',
    allowedMethod: [
      {
        method: 'Debit and Credit Cards',
        code: 'card',
        provider: ['Visa', 'Mastercard'],
        enabled: true,
      },
      {
        method: 'FPX',
        code: 'fpx',
        provider: [],
        enabled: true,
      },
      {
        method: 'Wallets',
        code: 'wallet',
        provider: ['TouchnGo', 'GrabPay'],
        enabled: true,
      },
    ],
  },
};
export default settingsData;
