export const authRole = {
  Admin: ['admin', 'super-admin'],
  User: ['user', 'admin', 'staff', 'parents'],
};

export const RoutePermittedRole = {
  Admin: 'admin',
  User: 'user',
  Staff: 'staff',
  Supervisor: 'supervisor',
  Account: 'account',
  Management: 'management',
};
export const defaultUser = {
  displayName: 'John Alex',
  email: 'demo@example.com',
  token: 'access-token',
  role: 'user',
  photoURL: '/assets/images/avatar/A11.jpg',
};
export const fileStackKey = 'Ach6MsgoQHGK6tCaq5uJgz';
export const initialUrl = '/dashboard'; // this url will open after login
export const landingUrl = '/dashboard';
export const otpTestingEnabled =
  process.env.REACT_APP_OTP_TESTING_ENABLED === 'true';

export const RoutePermittedRole2 = {
  dashboard_branch_view: 'dashboard_branch_view',
  dashboard_management_view: 'dashboard_management_view',
  dashboard_finance_view: 'dashboard_finance_view',
  dashboard_sales_view: 'dashboard_sales_view',
  dashboard_crm_view: 'dashboard_crm_view',
  dashboard_marketing_view: 'dashboard_marketing_view',
  admin_role_view: 'admin_role_view',
  admin_role_update: 'admin_role_update',
  admin_role_create: 'admin_role_create',
  admin_role_delete: 'admin_role_delete',
  admin_area_view: 'admin_area_view',
  admin_area_update: 'admin_area_update',
  admin_area_create: 'admin_area_create',
  admin_area_delete: 'admin_area_delete',
  admin_branch_view: 'admin_branch_view',
  admin_branch_create: 'admin_branch_create',
  admin_branch_update: 'admin_branch_update',
  admin_branch_delete: 'admin_branch_delete',
  admin_room_view: 'admin_room_view',
  admin_room_create: 'admin_room_create',
  admin_room_update: 'admin_room_update',
  admin_room_delete: 'admin_room_delete',
  admin_package_view: 'admin_package_view',
  admin_package_create: 'admin_package_create',
  admin_package_update: 'admin_package_update',
  admin_package_delete: 'admin_package_delete',
  admin_banner_view: 'admin_banner_view',
  admin_banner_update: 'admin_banner_update',
  admin_banner_create: 'admin_banner_create',
  admin_banner_delete: 'admin_banner_delete',
  admin_message_view: 'admin_message_view',
  admin_message_update: 'admin_message_update',
  admin_message_create: 'admin_message_create',
  admin_message_delete: 'admin_message_delete',
  admin_voucher_view: 'admin_voucher_view',
  admin_voucher_update: 'admin_voucher_update',
  admin_voucher_create: 'admin_voucher_create',
  admin_voucher_delete: 'admin_voucher_delete',
  member_member_view: 'member_member_view',
  member_member_create: 'member_member_create',
  member_member_update: 'member_member_update',
  member_member_delete: 'member_member_delete',
  member_transfer_view: 'member_transfer_view',
  member_transfer_create: 'member_transfer_create',
  member_transfer_update: 'member_transfer_update',
  member_transfer_delete: 'member_transfer_delete',
  member_booking_view: 'member_booking_view',
  member_booking_create: 'member_booking_create',
  member_booking_update: 'member_booking_update',
  member_booking_delete: 'member_booking_delete',
  member_checkin_view: 'member_checkin_view',
  member_checkin_create: 'member_checkin_create',
  member_checkin_update: 'member_checkin_update',
  member_checkin_delete: 'member_checkin_delete',
  member_feedback_view: 'member_feedback_view',
  member_feedback_create: 'member_feedback_create',
  member_feedback_update: 'member_feedback_update',
  member_feedback_delete: 'member_feedback_delete',
  member_otp_testing_view: 'member_otp_testing_view',
  finance_sales_view: 'finance_sales_view',
  finance_sales_create: 'finance_sales_create',
  finance_sales_update: 'finance_sales_update',
  finance_sales_delete: 'finance_sales_delete',
  finance_payments_view: 'finance_payments_view',
  finance_payments_update: 'finance_payments_update',
  finance_payments_create: 'finance_payments_create',
  finance_payments_delete: 'finance_payments_delete',
  admin_staff_view: 'admin_staff_view',
  admin_staff_update: 'admin_staff_update',
  admin_staff_create: 'admin_staff_create',
  admin_staff_delete: 'admin_staff_delete',
  hr_attendance_view: 'hr_attendance_view',
  hr_attendance_update: 'hr_attendance_update',
  hr_attendance_create: 'hr_attendance_create',
  hr_attendance_delete: 'hr_attendance_delete',
  finance_report_view: 'finance_report_view',
  finance_report_create: 'finance_report_create',
  finance_report_update: 'finance_report_update',
};
